# MCP Go Agent Configuration

# Server settings
server:
  port: 9090
  host: 0.0.0.0
  metrics_port: 9091
  log_level: info
  debug: false
  cors:
    allowed_origins:
      - "*"
    allowed_methods:
      - "GET"
      - "POST"
      - "OPTIONS"
    allowed_headers:
      - "*"

# Database settings
database:
  connection_string: "postgres://demo:demo@db:5432/demo?sslmode=disable"
  max_connections: 10
  connection_timeout: 5s
  idle_timeout: 60s

# MCP Protocol settings
mcp:
  protocol_version: "2.0"
  server_name: "Go MCP Server"
  server_version: "1.0.0"
  capabilities:
    supported_languages:
      - "go"
      - "sql"
    supports_notebooks: true
    supports_streaming: true

# Logging
logging:
  format: json
  output: stdout
  file: /var/log/mcp-go-agent.log
  rotation:
    max_size: 10 # MB
    max_backups: 3
    max_age: 7 # days

# Monitoring
monitoring:
  prometheus: true
  health_check_interval: 30s
  health_check_timeout: 10s
