version: '3.8'
services:
  mcp-go:
    image: ghcr.io/centralmind/gateway:v0.2.14
    ports:
      - "9090:9090"
      - "9091:9091"  # Metrics port
    volumes:
      - ./go/config.yaml:/app/config.yaml
      - ./go/logs:/var/log
    environment:
      - CONFIG_FILE=/app/config.yaml
      - LOG_LEVEL=info
      - DEBUG=false
      - MCP_SERVER_NAME=Go MCP Server
      - MCP_SERVER_VERSION=1.0.0
    command: start --config /app/config.yaml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    depends_on:
      - db
